# Generated by scripts/generate_catalog.py. Do not edit.
from enum import StrEnum


class DocType(StrEnum):
    """DRS document type codes. Members are strings and work anywhere a code does."""

    ORDER_8900_1_EDITORIAL_CORRECTIONS = "8900.1_EDITORIAL_CORRECTIONS"
    """Editorial Corrections."""

    ORDER_8900_1_SUMMARY_OF_CHANGES = "8900.1_SUMMARY_OF_CHANGES"
    """Summary of Changes."""

    AB = "AB"
    """Air Commerce Regulations/Aeronautics Bulletins (AB)."""

    AC = "AC"
    """Advisory Circulars (AC)."""

    ACCEPTED_CONSENSUS_STANDARDS = "ACCEPTED_CONSENSUS_STANDARDS"
    """Accepted Consensus Standards/Notices of Availability."""

    ADFRAWD = "ADFRAWD"
    """AD Final Rules."""

    ADFREAD = "ADFREAD"
    """Emergency ADs (EAD)."""

    ADNPRM = "ADNPRM"
    """AD Notice of Proposed Rulemaking (AD NPRM)."""

    AFS_1_MEMORANDUMS = "AFS-1_MEMORANDUMS"
    """AFX Memorandums. Internal only."""

    AFS_FFS_UPDATEPUB = "AFS_FFS_UPDATEPUB"
    """Future of Flight Standards (FFS) UpdatePub."""

    AFS_FFS_UPDATES = "AFS_FFS_UPDATES"
    """FFS Updates. Internal only."""

    AFS_FOCUS_TEAMS = "AFS_FOCUS_TEAMS"
    """Focus Teams."""

    AFS_POLICY_DEV_MEMOS = "AFS_POLICY_DEV_MEMOS"
    """Flight Standards Policy Deviation Memorandums. Internal only."""

    AIRCRAFT_MASTER_SCHEDULE = "AIRCRAFT_MASTER_SCHEDULE"
    """Aircraft Master Schedule."""

    AIRCRAFT_STANDARDIZED_CURRICULUM = "AIRCRAFT_STANDARDIZED_CURRICULUM"
    """Aircraft-Specific Standardized Curriculum."""

    AIRPORT_AC = "AIRPORT_AC"
    """Airport Advisory Circulars (AC)."""

    AIRWORTHINESS_CONCERN_SHEETS = "AIRWORTHINESS_CONCERN_SHEETS"
    """Airworthiness Concern Sheets (ACS)."""

    AIR_POLICY = "AIR_POLICY"
    """AIR Policy Statements, Memos and Deviations."""

    AIR_QMS_PROCESSES = "AIR_QMS_PROCESSES"
    """AIR QMS Processes. Internal only."""

    ALERTS = "ALERTS"
    """Aviation Maintenance Alerts Data."""

    AOV_JOB_AIDS = "AOV_JOB_AIDS"
    """Job Aids (AOV). Internal only."""

    AOV_SAFETY_OVERSIGHT_CIRCULAR = "AOV_SAFETY_OVERSIGHT_CIRCULAR"
    """Safety Oversight Circulars (SOC). Internal only."""

    AOV_WORK_INSTRUCTIONS = "AOV_WORK_INSTRUCTIONS"
    """Work Instructions (AOV). Internal only."""

    AT_JTA = "AT_JTA"
    """Air Transportation Job Task Analysis (Historical AT JTA). Internal only."""

    AVP_POLICY = "AVP_POLICY"
    """AVP Policy Statements, Memos and Deviations."""

    BULLETINS = "BULLETINS"
    """Handbook, Information and Policy Subsystem Bulletins."""

    CAM = "CAM"
    """Civil Aeronautics Manuals (CAM)."""

    CANIC = "CANIC"
    """Continued Airworthiness Notification to the International Community (CANIC)."""

    CAR = "CAR"
    """Civil Air Regulations (CARs)."""

    CATA_WORKLIST_ITEM = "CATA_WORKLIST_ITEM"
    """CATA Worklist Item (CWI) Decision Documents."""

    CFRFRSFAR = "CFRFRSFAR"
    """Final Rules."""

    CIVIL_PENALTY_APPEALS = "CIVIL_PENALTY_APPEALS"
    """Civil Penalty Appeals."""

    ELOS = "ELOS"
    """Equivalent Levels of Safety (ELOS)."""

    ENVIRONMENTAL_SUPPORTING_DOCUMENTS = "ENVIRONMENTAL_SUPPORTING_DOCUMENTS"
    """Environmental Supporting Documents."""

    EXEMPTION = "EXEMPTION"
    """Exemptions."""

    FAR = "FAR"
    """Title 14 CFR By Part and Section."""

    FIRE_TEST_HANDBOOK = "FIRE_TEST_HANDBOOK"
    """Aircraft Materials Fire Test Handbook."""

    FIRE_TEST_HANDBOOK_REVISION3 = "FIRE_TEST_HANDBOOK_REVISION3"
    """Aircraft Materials Fire Test Handbook - Revision 3."""

    FOEB = "FOEB"
    """Flight Operations Evaluation Board (FOEB) Announcements."""

    FSB_REPORTS = "FSB_REPORTS"
    """Flight Standardization Board Reports (FSBR)."""

    FS_POLICY = "FS_POLICY"
    """FS Policy Statements, Memos and Deviations."""

    GA_JTA = "GA_JTA"
    """General Aviation Job Task Analysis (Historical GA JTA). Internal only."""

    ICAO_ANNEX = "ICAO_ANNEX"
    """ICAO Annexes. Internal only."""

    ICAO_DOCUMENT = "ICAO_DOCUMENT"
    """ICAO Documents. Internal only."""

    ICAO_OTHER_PUBLICATIONS = "ICAO_OTHER_PUBLICATIONS"
    """ICAO - Other Publications. Internal only."""

    ICAO_PANS = "ICAO_PANS"
    """ICAO Procedures for Air Navigation Services (PANS). Internal only."""

    INFO = "INFO"
    """Information for Operators (InFO)."""

    JOB_TASKS = "JOB_TASKS"
    """Job Tasks (JT). Internal only."""

    LAUNCH_SITE_OPERATOR_LICENSES = "LAUNCH_SITE_OPERATOR_LICENSES"
    """Sites."""

    LAUNCH_VEHICLE_OPERATOR_LICENSES = "LAUNCH_VEHICLE_OPERATOR_LICENSES"
    """Vehicles."""

    LEGAL_INTERPRETATIONS = "LEGAL_INTERPRETATIONS"
    """Legal Interpretations."""

    MMEL = "MMEL"
    """Master Minimum Equipment Lists (MMEL)."""

    MMEL_POLICY_LETTERS = "MMEL_POLICY_LETTERS"
    """Master Minimum Equipment List Policy Letters (MMEL PL)."""

    NORSEE = "NORSEE"
    """14 CFR Part 21.8(d) / NORSEE Approvals."""

    NOTICES = "NOTICES"
    """Notices."""

    NPRM = "NPRM"
    """Notices of Proposed Rulemaking (NPRM)."""

    OPSS_GUIDANCE = "OPSS_GUIDANCE"
    """Operations Safety System (OPSS) Documents."""

    ORDERS = "ORDERS"
    """Orders."""

    ORDER_8300_10 = "ORDER_8300.10"
    """Order 8300.10, Airworthiness Inspector’s Handbook."""

    ORDER_8400_10 = "ORDER_8400.10"
    """Order 8400.10, Air Transportation Operations Inspectors Handbook."""

    ORDER_8700_1 = "ORDER_8700.1"
    """Order 8700.1, General Aviation Safety Inspectors Handbook."""

    ORDER_8740_1 = "ORDER_8740.1"
    """Order 8740.1, FAA Safety Team Program Manager’s Handbook."""

    ORDER_8900_1 = "ORDER_8900.1"
    """8900.1, Contents."""

    OSR = "OSR"
    """Operational Suitability Reports (OSR)."""

    OSWG = "OSWG"
    """Operations Specification Working Group (OSWG)."""

    OTHER_AWARDS_INFORMATION_GUIDES = "OTHER_AWARDS_INFORMATION_GUIDES"
    """Awards Information Guides (AIG)."""

    OTHER_AWO = "OTHER_AWO"
    """All Weather Operations (AWO) Specialists. Internal only."""

    OTHER_CPD_6_03 = "OTHER_CPD_6.03"
    """FAA Air Carrier Certification Process Certification Process Document (CPD) 6.03. Internal only."""

    OTHER_EFB_CHECKLISTS = "OTHER_EFB_CHECKLISTS"
    """Electronic Flight Bag (EFB) Checklist."""

    OTHER_EFB_RESEARCH_REPORTS = "OTHER_EFB_RESEARCH_REPORTS"
    """Electronic Flight Bag (EFB) Research Reports."""

    OTHER_FAA_90_DAY_SAFETY_REVIEW = "OTHER_FAA_90_DAY_SAFETY_REVIEW"
    """FAA 90-Day Safety Review."""

    OTHER_FLIGHT_STANDARDS_ORM_WORKSHEETS = "OTHER_FLIGHT_STANDARDS_ORM_WORKSHEETS"
    """Flight Standards Preflight Operational Risk Matrix (ORM) Worksheets. Internal only."""

    OTHER_INFORMATION_GUIDES = "OTHER_INFORMATION_GUIDES"
    """Information Guides."""

    OTHER_INTERNATIONAL_PUBLICATIONS = "OTHER_INTERNATIONAL_PUBLICATIONS"
    """International Agreements."""

    OTHER_JOB_AIDS = "OTHER_JOB_AIDS"
    """Job Aids."""

    OTHER_LASER_INVESTIGATION_REFERENCES = "OTHER_LASER_INVESTIGATION_REFERENCES"
    """Laser Investigation References. Internal only."""

    OTHER_PROCEDURES_MANUAL = "OTHER_PROCEDURES_MANUAL"
    """Program Tracking and Reporting Subsystem (PTRS) Procedures Manual (PPM). Internal only."""

    OTHER_PS_FEDERAL_AVIATION_ACTS = "OTHER_PS_FEDERAL_AVIATION_ACTS"
    """PS Federal Aviation Acts Data."""

    OTHER_PS_LEGAL_INTERPRETATIONS = "OTHER_PS_LEGAL_INTERPRETATIONS"
    """Inactive Legal Interpretations. Internal only."""

    OTHER_PS_POLICY_MEMORANDA = "OTHER_PS_POLICY_MEMORANDA"
    """PS Policy Memoranda. Internal only."""

    OTHER_PS_PREAMBLES = "OTHER_PS_PREAMBLES"
    """PS Preambles. Internal only."""

    OTHER_QMS_AND_BP = "OTHER_QMS_AND_BP"
    """Flight Standards (FS) QMS Processes. Internal only."""

    OTHER_RCCB = "OTHER_RCCB"
    """Regulatory Consistency Communication Board (RCCB) Determinations."""

    OTHER_RIRTP = "OTHER_RIRTP"
    """Runway Incursion Remedial Training Program (RIRTP). Internal only."""

    OTHER_SPRS = "OTHER_SPRS"
    """Supplemental Passenger Restraint Systems (SPRS). Internal only."""

    OTHER_VPM = "OTHER_VPM"
    """Vital Information Subsystem Procedures Manual (VPM). Internal only."""

    PART_129_OPSPEC_JA = "PART_129_OPSPEC_JA"
    """Part 129 Operations Specification (OpSpec) Job Aids."""

    PERMITS = "PERMITS"
    """Experimental Permits."""

    PILOT_QUALIFICATION_CURRICULUM = "PILOT_QUALIFICATION_CURRICULUM"
    """Instructor/Check Pilot Qualification Curriculum."""

    PMA = "PMA"
    """Parts Manufacturer Approvals (PMA)."""

    POLICY = "POLICY"
    """AVS Policy Statements, Memos and Deviations."""

    SAFETY_ELEMENT_APPROVALS = "SAFETY_ELEMENT_APPROVALS"
    """Safety Element Approvals."""

    SAFO = "SAFO"
    """Safety Alerts for Operators (SAFO)."""

    SAIB = "SAIB"
    """Special Airworthiness Information Bulletins (SAIB)."""

    SAS_AXH_DCT = "SAS_AXH_DCT"
    """SAS AXH Data Collection Tool (DCT)."""

    SAS_DCT = "SAS_DCT"
    """SAS FS Data Collection Tool (DCT)."""

    SCFINAL = "SCFINAL"
    """Special Conditions (Final)."""

    SCPROPOSED = "SCPROPOSED"
    """Special Conditions (Proposed)."""

    SFAR = "SFAR"
    """Special Federal Aviation Regulations (SFAR)."""

    STC = "STC"
    """Supplemental Type Certificates (STC)."""

    STCRELIEFAPPLETTER = "STCRELIEFAPPLETTER"
    """STC Relief Approval Letters."""

    TCDSMODEL = "TCDSMODEL"
    """Type Certificate Data Sheets (TCDS)."""

    TSO = "TSO"
    """Technical Standard Orders (TSO)."""

    TSOI = "TSOI"
    """Technical Standard Order Authorizations (TSOA) and Letters of Design Approval (LODA)."""

    UNAPPROVED_PARTS_NOTIFICATIONS = "UNAPPROVED_PARTS_NOTIFICATIONS"
    """Unapproved Parts Notifications (UPN)."""
